server:
   port: 8083
   
spring:
  cloud:
    stream:
      bindings:
        inboundCardChanges:
          destination: cardChangeTopic
          content-type: application/json
        binder:
          zkNodes: localhost
          brokers: localhost
  zipkin:
    baseUrl:  http://localhost:9411

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

security:
  basic:
    enabled: false

logging:
    level:
      com.netflix: WARN
      org.springframework.web: WARN
      com.tianyalan: INFO
